release_25_3_4:
  gpu_operator_version: v25.3.4
  gpu_driver_version: 580.82.07
  driver_manager_version: 0.8.0
  container_toolkit: v1.17.8
  device_plugin: v0.17.3
  dcgm_exporter_version: 4.2.3-4.1.3
  nfd_version: v0.17.2
  gfd_version: v0.17.1
  mig_manager_version: v0.12.2
  dcgm_version: 4.2.3-1
  validator_version: v25.3.4
  gds_driver: 2.20.5
release_25_3_2:
  gpu_operator_version: v25.3.2
  gpu_driver_version: 580.65.06
  driver_manager_version: 0.8.0
  container_toolkit: v1.17.8
  device_plugin: v0.17.3
  dcgm_exporter_version: 4.2.3-4.1.3
  nfd_version: v0.17.2
  gfd_version: v0.17.1
  mig_manager_version: v0.12.2
  dcgm_version: 4.2.3-1
  validator_version: v25.3.2
  gds_driver: 2.20.5
release_25_3_1:
  gpu_operator_version: v25.3.1
  gpu_driver_version: 570.158.01
  driver_manager_version: 0.8.0
  container_toolkit: v1.17.8
  device_plugin: v0.17.2
  dcgm_exporter_version: 4.2.3-4.1.3
  nfd_version: v0.17.2
  gfd_version: v0.17.1
  mig_manager_version: v0.12.1
  dcgm_version: 4.2.3-1
  validator_version: v25.3.1
  gds_driver: 2.20.5
release_25_3_0:
  gpu_operator_version: v25.3.0
  gpu_driver_version: 570.124.06
  driver_manager_version: 0.8.0
  container_toolkit: v1.17.5
  device_plugin: v0.17.1
  dcgm_exporter_version: 4.1.1-4.0.4
  nfd_version: v0.17.2
  gfd_version: v0.17.1
  mig_manager_version: v0.12.1
  dcgm_version: 4.1.1-2
  validator_version: v25.3.0
  gds_driver: 2.20.5
release_24_9_2:
  gpu_operator_version: v24.9.2
  gpu_driver_version: 550.144.03
  driver_manager_version: 0.7.0
  container_toolkit: v1.17.4
  device_plugin: v0.17.0
  dcgm_exporter_version: 3.3.9-3.6.1
  nfd_version: v0.16.6
  gfd_version: v0.17.0
  mig_manager_version: v0.10.0
  dcgm_version: 3.3.9-1
  validator_version: v24.9.2
  gds_driver: 2.20.5
release_24_9_1:
  gpu_operator_version: v24.9.0
  gpu_driver_version: 550.127.05
  driver_manager_version: 0.7.0
  container_toolkit: v1.17.3
  device_plugin: v0.17.0
  dcgm_exporter_version: 3.3.9-3.6.1
  nfd_version: v0.16.6
  gfd_version: v0.17.0
  mig_manager_version: v0.10.0
  dcgm_version: 3.3.9-1
  validator_version: v24.9.0
  gds_driver: 2.20.5
release_24_9_0:
  gpu_operator_version: v24.9.0
  gpu_driver_version: 550.127.05
  driver_manager_version: 0.7.0
  container_toolkit: v1.17.0
  device_plugin: v0.17.0
  dcgm_exporter_version: 3.3.8-3.6.0
  nfd_version: v0.16.6
  gfd_version: v0.17.0
  mig_manager_version: v0.10.0
  dcgm_version: 3.3.8-1
  validator_version: v24.9.0
  gds_driver: 2.20.5
release_24_6_2:
  gpu_operator_version: v24.6.2
  gpu_driver_version: 550.90.07
  driver_manager_version: 0.6.8
  container_toolkit: v1.16.2
  device_plugin: v0.16.1
  dcgm_exporter_version: 3.3.7-3.5.0
  nfd_version: v0.16.3
  gfd_version: v0.16.1
  mig_manager_version: v0.8.0
  dcgm_version: 3.3.7-1
  validator_version: v24.6.2
  gds_driver: 2.17.5
release_24_6_0:
  gpu_operator_version: v24.6.0
  gpu_driver_version: 550.90.07
  driver_manager_version: 0.6.8
  container_toolkit: v1.16.1
  device_plugin: v0.16.1
  dcgm_exporter_version: 3.3.7-3.5.0
  nfd_version: v0.16.3
  gfd_version: v0.16.1
  mig_manager_version: v0.8.0
  dcgm_version: 3.3.7-1
  validator_version: v24.6.0
  gds_driver: 2.17.5
release_24_3_0:
  gpu_operator_version: v24.3.0
  gpu_driver_version: 550.54.14
  driver_manager_version: 0.6.8
  container_toolkit: v1.15.0
  device_plugin: v0.15.0
  dcgm_exporter_version: 3.3.5-3.4.1
  nfd_version: v0.15.4
  gfd_version: v0.15.0
  mig_manager_version: v0.7.0
  dcgm_version: 3.3.5-1
  validator_version: v24.3.0
  gds_driver: 2.17.5
release_23_9_2:
  gpu_operator_version: v23.9.2
  gpu_driver_version: 550.54.14
  driver_manager_version: 0.6.4
  container_toolkit: v1.14.6
  device_plugin: v0.14.5
  dcgm_exporter_version: 3.3.0-3.2.0
  nfd_version: v0.14.2
  gfd_version: v0.8.2
  mig_manager_version: v0.6.0
  dcgm_version: 3.2.6-1
  validator_version: v23.9.2
  gds_driver: 2.16.1
release_23_9_1:
  gpu_operator_version: v23.9.1
  gpu_driver_version: 535.129.03
  driver_manager_version: 0.6.4
  container_toolkit: v1.14.3
  device_plugin: v0.14.2
  dcgm_exporter_version: 3.3.0-3.2.0
  nfd_version: v0.14.2
  gfd_version: v0.8.2
  mig_manager_version: v0.5.5
  dcgm_version: 3.2.6-1
  validator_version: v23.9.1
  gds_driver: 2.16.1
release_23_6_0:
  gpu_operator_version: v23.6.1
  gpu_driver_version: 535.104.05
  driver_manager_version: 0.6.1
  container_toolkit: v1.13.4
  device_plugin: v0.14.1
  dcgm_exporter_version: 3.1.8-3.1.5
  nfd_version: v0.13.1
  gfd_version: v0.8.1
  mig_manager_version: v0.5.3
  dcgm_version: 3.1.8-1
  validator_version: v23.6.1
  gds_driver: 2.15.1
release_23_3_2:
  gpu_operator_version: v23.3.2
  gpu_driver_version: 535.54.03
  driver_manager_version: 0.6.1
  container_toolkit: v1.13.0
  device_plugin: v0.14.0
  dcgm_exporter_version: 3.1.7-3.1.4
  nfd_version: v0.12.1
  gfd_version: v0.8.0
  mig_manager_version: v0.5.2
  dcgm_version: 3.1.7-1
  validator_version: v23.3.2
  gds_driver: 2.15.1
release_23_3_1:
  gpu_operator_version: v23.3.1
  gpu_driver_version: 525.105.17
  driver_manager_version: 0.6.1
  container_toolkit: v1.13.0
  device_plugin: v0.14.0
  dcgm_exporter_version: 3.1.7-3.1.4
  nfd_version: v0.12.1
  gfd_version: v0.8.0
  mig_manager_version: v0.5.2
  dcgm_version: 3.1.7-1
  validator_version: v23.3.1
  gds_driver: 2.15.1
release_22_9_2:
  gpu_operator_version: v22.9.1
  gpu_driver_version: 525.85.12
  driver_manager_version: 0.6.0
  container_toolkit: v1.11.0
  device_plugin: v0.13.0
  dcgm_exporter_version: 3.1.3-3.1.2
  nfd_version: v0.10.1
  gfd_version: v0.7.0
  mig_manager_version: v0.5.0
  dcgm_version: 3.1.3-1
  validator_version: v22.9.1
  gds_driver: 2.14.13
release_22_9_1:
  gpu_operator_version: v22.9.1
  gpu_driver_version: 525.60.13
  driver_manager_version: 0.5.1
  container_toolkit: v1.11.0
  device_plugin: v0.13.0
  dcgm_exporter_version: 3.1.3-3.1.2
  nfd_version: v0.10.1
  gfd_version: v0.7.0
  mig_manager_version: v0.5.0
  dcgm_version: 3.1.3-1
  validator_version: v22.9.1
  gds_driver: 2.14.13
release_22_09:
  gpu_operator_version: v22.9.0
  gpu_driver_version: 520.61.07
  driver_manager_version: 0.4.1
  container_toolkit: v1.11.0
  device_plugin: v0.12.3
  dcgm_exporter_version: 3.0.4-3.0.0
  nfd_version: v0.10.1
  gfd_version: v0.6.2
  mig_manager_version: v0.5.0
  dcgm_version: 3.0.4-1
  validator_version: v22.9.0
release_1_11_0:
  gpu_operator_version: v1.11.0
  gpu_driver_version: 515.48.07
  driver_manager_version: 0.4.0
  container_toolkit: v1.10.0
  device_plugin: v0.12.2
  dcgm_exporter_version: 2.4.5-2.6.7
  nfd_version: v0.10.1
  gfd_version: v0.6.1
  mig_manager_version: v0.4.2
  dcgm_version: 2.4.5-1
  validator_version: v1.11.0
  kubevit_device_plugin: 1.1.2
  device_manager_version: 0.1.0
release_1_10:
  gpu_operator_version: v1.10.1
  gpu_driver_version: 510.47.03
  driver_manager_version: 0.3.0
  container_toolkit: v1.9.0
  device_plugin: v0.11.0
  dcgm_exporter_version: 2.3.4-2.6.4
  nfd_version: v0.10.1
  gfd_version: v0.5.0
  mig_manager_version: v0.3.0
  dcgm_version: 2.3.4.1
  validator_version: v1.10.1